<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class OnlineTableTypeRequest extends FormRequest
{

    public function rules(): array
    {
        return [
            'table_config.headerTitle' => 'required|string',
            'table_config.tooltip' => 'required|string',
            'table_config.size' => 'nullable|in:small,middle,large',
            'table_config.addShow' => 'required|boolean',
            'table_config.editShow' => 'required|boolean',
            'table_config.deleteShow' => 'required|boolean',
            'table_config.rowSelectionShow' => 'required|boolean',
            'table_config.bordered' => 'required|boolean',
            'table_config.showHeader' => 'required|boolean',
            'table_config.searchShow' => 'nullable|boolean',
            'table_config.search' => 'exclude_unless:table_config.searchShow,true|array',
            'table_config.search.resetText' => 'required_with:table_config.search',
            'table_config.search.searchText' => 'required_with:table_config.search',
            'table_config.search.span' => 'required_with:table_config.search|integer',
            'table_config.search.layout' => 'required_with:table_config.search|in:vertical,horizontal',
            'table_config.search.filterType' => 'required_with:table_config.search|in:query,light',
            'table_config.optionsShow' => 'nullable|boolean',
            'table_config.options' => 'exclude_unless:table_config.optionsShow,true|array',
            'table_config.options.density' => 'required_with:table_config.options|boolean',
            'table_config.options.search' => 'required_with:table_config.options|boolean',
            'table_config.options.fullScreen' => 'required_with:table_config.options|boolean',
            'table_config.options.setting' => 'required_with:table_config.options|boolean',
            'table_config.options.reload' => 'required_with:table_config.options|boolean',
            'table_config.paginationShow' => 'nullable|boolean',
            'table_config.pagination' => 'exclude_unless:table_config.paginationShow,true|array',
            'table_config.pagination.size' => 'required_with:table_config.pagination|in:default,small',
            'table_config.pagination.simple' => 'nullable|boolean',
            'crud_config.name' => 'required|string',
            'crud_config.controllerPath' => 'nullable|string',
            'crud_config.modelPath' => 'nullable|string',
            'crud_config.validatePath' => 'nullable|string',
            'crud_config.pagePath' => 'nullable|string',
            'crud_config.sqlTableName' => 'required|string',
            'crud_config.sqlTableRemark' => 'required|string',
            'crud_config.autoDeletetime' => 'nullable|boolean',
            'columns.*.key' => 'nullable|string',
            'columns.*.valueType' => 'nullable|string',
            'columns.*.dataIndex' => 'nullable|string',
            'columns.*.title' => 'nullable|string',
            'columns.*.select' => 'nullable|string',
            'columns.*.validation' => 'nullable|array',
            'columns.*.hideInSearch' => 'nullable|boolean',
            'columns.*.hideInTable' => 'nullable|boolean',
            'columns.*.hideInForm' => 'nullable|boolean',
            'columns.*.enum' => 'nullable|string',
            'columns.*.defaultValue' => 'nullable|string',
            'columns.*.sqlType' => 'nullable|string',
            'columns.*.sqlLength' => 'nullable',
            'columns.*.isKey' => 'nullable|boolean',
            'columns.*.null' => 'nullable|boolean',
            'columns.*.autoIncrement' => 'nullable|boolean',
            'columns.*.unsign' => 'nullable|boolean',
            'columns.*.mock' => 'nullable|string',
            'id' => 'required|string|int',
        ];
    }

    public function messages(): array
    {
        return [
            'table_config.headerTitle.required' => '表格标题是必填项。',
            'table_config.headerTitle.string' => '表格标题必须是字符串。',
            'table_config.tooltip.required' => '表格提示是必填项。',
            'table_config.tooltip.string' => '表格提示必须是字符串。',
            'table_config.size.in' => '指定的表格大小无效，只能是 small, middle, large 或 为空。',
            'table_config.size.nullable' => '表格大小字段可选。',
            'table_config.addShow.required' => '新增显示开关是必填项。',
            'table_config.addShow.boolean' => '新增显示必须是布尔值。',
            'table_config.editShow.required' => '编辑显示开关是必填项。',
            'table_config.editShow.boolean' => '编辑显示必须是布尔值。',
            'table_config.deleteShow.required' => '删除显示开关是必填项。',
            'table_config.deleteShow.boolean' => '删除显示必须是布尔值。',
            'table_config.rowSelectionShow.required' => '多选显示开关是必填项。',
            'table_config.rowSelectionShow.boolean' => '多选显示必须是布尔值。',
            'table_config.bordered.required' => '边框显示开关是必填项。',
            'table_config.bordered.boolean' => '边框显示必须是布尔值。',
            'table_config.showHeader.required' => '表头显示开关是必填项。',
            'table_config.showHeader.boolean' => '表头显示必须是布尔值。',
            'table_config.searchShow.boolean' => '查询开关必须是布尔值。',
            'table_config.search.array' => '查询配置必须是数组格式。',
            'table_config.search.resetText.required_with' => '查询配置启用时，重置按钮文案是必填项。',
            'table_config.search.searchText.required_with' => '查询配置启用时，查询按钮文案是必填项。',
            'table_config.search.span.required_with' => '查询配置启用时，表单栅格设置是必填项。',
            'table_config.search.span.integer' => '表单栅格必须是整数。',
            'table_config.search.layout.required_with' => '查询配置启用时，表单布局是必填项。',
            'table_config.search.layout.in' => '表单布局必须是 vertical 或 horizontal。',
            'table_config.search.filterType.required_with' => '查询配置启用时，表单类型是必填项。',
            'table_config.search.filterType.in' => '表单类型必须是 query 或 light。',
            'table_config.optionsShow.boolean' => '操作栏显示开关必须是布尔值。',
            'table_config.options.array' => '操作栏配置必须是数组格式。',
            'table_config.options.density.required_with' => '操作栏配置启用时，密度按钮设置是必填项。',
            'table_config.options.density.boolean' => '密度按钮设置必须是布尔值。',
            'table_config.options.search.required_with' => '操作栏配置启用时，搜索按钮是必填项。',
            'table_config.options.search.boolean' => '搜索按钮必须是布尔值。',
            'table_config.options.fullScreen.required_with' => '操作栏配置启用时，全屏按钮是必填项。',
            'table_config.options.fullScreen.boolean' => '全屏按钮必须是布尔值。',
            'table_config.options.setting.required_with' => '操作栏配置启用时，列设置是必填项。',
            'table_config.options.setting.boolean' => '列设置必须是布尔值。',
            'table_config.options.reload.required_with' => '操作栏配置启用时，刷新按钮是必填项。',
            'table_config.options.reload.boolean' => '刷新按钮必须是布尔值。',
            'table_config.paginationShow.boolean' => '分页显示开关必须是布尔值。',
            'table_config.pagination.array' => '分页配置必须是数组格式。',
            'table_config.pagination.size.required_with' => '分页配置启用时，分页大小是必填项。',
            'table_config.pagination.size.in' => '分页大小必须是 default 或 small。',
            'table_config.pagination.simple.boolean' => '简洁分页必须是布尔值。',
            'crud_config.name.string' => '名称必须是字符串。',
            'crud_config.controllerPath.string' => '控制器路径必须是字符串。',
            'crud_config.modelPath.string' => '模型路径必须是字符串。',
            'crud_config.validatePath.string' => '验证路径必须是字符串。',
            'crud_config.pagePath.string' => '页面路径必须是字符串。',
            'crud_config.sqlTableName.string' => 'SQL表名必须是字符串。',
            'crud_config.sqlTableRemark.string' => 'SQL表备注必须是字符串。',
            'crud_config.autoDeletetime.boolean' => '自动删除时间开关必须是布尔值。',
            'columns.*.key.string' => '字段 KEY 必须是字符串。',
            'columns.*.valueType.string' => '字段类型必须是字符串。',
            'columns.*.dataIndex.string' => '数据库字段索引必须是字符串。',
            'columns.*.title.string' => '字段标题必须是字符串。',
            'columns.*.select.string' => '选择字段必须是字符串或者布尔值 false。',
            'columns.*.validation.array' => '验证规则必须是数组。',
            'columns.*.hideInSearch.boolean' => '在搜索中隐藏必须是布尔值。',
            'columns.*.hideInTable.boolean' => '在表格中隐藏必须是布尔值。',
            'columns.*.hideInForm.boolean' => '在表单中隐藏必须是布尔值。',
            'columns.*.defaultValue.string' => '默认值必须是字符串。',
            'columns.*.sqlType.string' => 'SQL类型必须是字符串。',
            'columns.*.sqlLength.integer' => 'SQL字段长度必须是整数。',
            'columns.*.isKey.boolean' => '是否主键必须是布尔值。',
            'columns.*.null.boolean' => '是否可以为NULL必须是布尔值。',
            'columns.*.autoIncrement.boolean' => '是否自增必须是布尔值。',
            'columns.*.unsign.boolean' => '是否无符号必须是布尔值。',
            'columns.*.mock.string' => '模拟数据必须是字符串。',
            'id.required' => 'ID是必填项。',
            'id.string' => 'ID必须是字符串或整数。'
        ];
    }
}
