export const dbTypes = {
  bigint: 'bigint',
  binary: 'binary',
  bit: 'bit',
  blob: 'blob',
  char: 'char',
  date: 'date',
  datetime: 'datetime',
  decimal: 'decimal',
  double: 'double',
  enum: 'enum',
  float: 'float',
  geography: 'geography',
  geometry: 'geometry',
  int: 'int',
  integer: 'integer',
  json: 'json',
  longblob: 'longblob',
  longtext: 'longtext',
  mediumblob: 'mediumblob',
  mediumint: 'mediumint',
  mediumtext: 'mediumtext',
  numeric: 'numeric',
  real: 'real',
  set: 'set',
  smallint: 'smallint',
  string: 'string',
  text: 'text',
  time: 'time',
  timestamp: 'timestamp',
  tinyblob: 'tinyblob',
  tinyint: 'tinyint',
  tinytext: 'tinytext',
  varbinary: 'varbinary',
  varchar: 'varchar',
  year: 'year',
  geomcollection: 'geomcollection',
  linestring: 'linestring',
  multilinestring: 'multilinestring',
  point: 'point',
  multipoint: 'multipoint',
  polygon: 'polygon',
  multipolygon: 'multipolygon',
  uuid: 'uuid',
  geometrycollection: 'geometrycollection',
};

export const valueTypes = {
  password: 'password',
  money: 'money',
  text: 'text',
  textarea: 'textarea',
  date: 'date',
  dateTime: 'dateTime',
  time: 'time',
  select: 'select',
  checkbox: 'checkbox',
  radio: 'radio',
  radioButton: 'radioButton',
  digit: 'digit',
  avatar: 'avatar',
  switch: 'switch',
  image: 'image',
};

export const defaultSql = {
  password: {
    default: undefined,
    length: 255,
    notNull: false,
    type: 'varchar',
    unsigned: undefined,
    autoincrement: undefined,
    precision: undefined,
    presetValues: undefined,
    scale: undefined,
  },
  money: {
    default: 0.00,
    length: undefined,
    notNull: true,
    type: 'decimal',
    unsigned: false,
    autoincrement: undefined,
    precision: 10,
    presetValues: undefined,
    scale: 2,
  },
  text: {
    default: undefined,
    length: 255,
    notNull: false,
    type: 'varchar',
    unsigned: undefined,
    autoincrement: undefined,
    precision: undefined,
    presetValues: undefined,
    scale: undefined,
  },
  textarea: {
    default: undefined,
    length: undefined,
    notNull: false,
    type: 'text',
    unsigned: undefined,
    autoincrement: undefined,
    precision: undefined,
    presetValues: undefined,
    scale: undefined,
  },
  time: {
    default: undefined,
    length: undefined,
    notNull: undefined,
    type: undefined,
    unsigned: undefined,
    autoincrement: undefined,
    precision: undefined,
    presetValues: undefined,
    scale: undefined,
  },
  date: {
    default: undefined,
    length: undefined,
    notNull: undefined,
    type: undefined,
    unsigned: undefined,
    autoincrement: undefined,
    precision: undefined,
    presetValues: undefined,
    scale: undefined,
  },
  dateTime: {
    default: undefined,
    length: undefined,
    notNull: undefined,
    type: undefined,
    unsigned: undefined,
    autoincrement: undefined,
    precision: undefined,
    presetValues: undefined,
    scale: undefined,
  },
  select: {
    default: undefined,
    length: undefined,
    notNull: undefined,
    type: undefined,
    unsigned: undefined,
    autoincrement: undefined,
    precision: undefined,
    presetValues: undefined,
    scale: undefined,
  },
  checkbox: {
    default: undefined,
    length: undefined,
    notNull: undefined,
    type: undefined,
    unsigned: undefined,
    autoincrement: undefined,
    precision: undefined,
    presetValues: undefined,
    scale: undefined,
  },
  radio: {
    default: undefined,
    length: undefined,
    notNull: undefined,
    type: undefined,
    unsigned: undefined,
    autoincrement: undefined,
    precision: undefined,
    presetValues: undefined,
    scale: undefined,
  },
  radioButton: {
    default: undefined,
    length: undefined,
    notNull: undefined,
    type: undefined,
    unsigned: undefined,
    autoincrement: undefined,
    precision: undefined,
    presetValues: undefined,
    scale: undefined,
  },
  digit: {
    default: undefined,
    length: undefined,
    notNull: undefined,
    type: undefined,
    unsigned: undefined,
    autoincrement: undefined,
    precision: undefined,
    presetValues: undefined,
    scale: undefined,
  },
  avatar: {
    default: undefined,
    length: undefined,
    notNull: undefined,
    type: undefined,
    unsigned: undefined,
    autoincrement: undefined,
    precision: undefined,
    presetValues: undefined,
    scale: undefined,
  },
  switch: {
    default: undefined,
    length: undefined,
    notNull: undefined,
    type: undefined,
    unsigned: undefined,
    autoincrement: undefined,
    precision: undefined,
    presetValues: undefined,
    scale: undefined,
  },
  image: {
    default: undefined,
    length: undefined,
    notNull: undefined,
    type: undefined,
    unsigned: undefined,
    autoincrement: undefined,
    precision: undefined,
    presetValues: undefined,
    scale: undefined,
  },

}
