/**
 * 默认 Sql 配置
 */
export const defaultSql: OnlineType.DefaultSqlList = [
  {
    valueType: 'text',
    title: '自增主键',
    dataIndex: 'id',
    select: '=',
    validation: [],
    hideInForm: true,
    hideInSearch: false,
    hideInTable: false,
    isKey: true,
    null: true,
    autoIncrement: true,
    sqlType: 'int',
  },
  {
    valueType: 'text',
    title: '文本框',
    dataIndex: 'text',
    select: 'like',
    validation: [],
    hideInForm: false,
    hideInSearch: false,
    hideInTable: false,
    defaultValue: 'empty string',
    isKey: false,
    null: false,
    sqlType: 'varchar',
    sqlLength: 50,
  },
  {
    valueType: 'textarea',
    title: '文本域',
    dataIndex: 'textarea',
    validation: [],
    hideInForm: false,
    hideInSearch: true,
    hideInTable: false,
    sqlType: 'text',
  },
  {
    valueType: 'password',
    title: '密码框',
    dataIndex: 'password',
    validation: [],
    hideInForm: false,
    hideInSearch: true,
    hideInTable: true,
    defaultValue: 'empty string',
    isKey: false,
    null: false,
    sqlType: 'varchar',
    sqlLength: 50,
  },
  {
    valueType: 'digit',
    title: '数字输入框',
    dataIndex: 'digit',
    validation: [],
    hideInForm: false,
    hideInSearch: false,
    hideInTable: false,
    defaultValue: 'null',
    isKey: false,
    null: false,
    sqlType: 'int',
    sqlLength: 10,
  },
  {
    valueType: 'switch',
    title: '开关',
    dataIndex: 'switch',
    select: '=',
    validation: [],
    hideInForm: false,
    hideInSearch: false,
    hideInTable: false,
    defaultValue: 'null',
    isKey: false,
    null: false,
    sqlType: 'int',
    sqlLength: 1,
  },
  {
    valueType: 'radio',
    title: '单选框',
    dataIndex: 'radio',
    select: '=',
    validation: [],
    hideInForm: false,
    hideInSearch: false,
    hideInTable: false,
    enum: '1:one\n2:two\n3:three',
    defaultValue: '1',
    isKey: false,
    null: false,
    sqlType: 'int',
    sqlLength: 2,
  },
  {
    valueType: 'radioButton',
    title: '按钮单选框',
    dataIndex: 'radioButton',
    select: '=',
    validation: [],
    hideInForm: false,
    hideInSearch: false,
    hideInTable: false,
    enum: '1:one\n2:two\n3:three',
    defaultValue: '1',
    isKey: false,
    null: false,
    sqlType: 'int',
    sqlLength: 2,
  },
  {
    valueType: 'checkbox',
    title: '多选框',
    dataIndex: 'checkbox',
    select: '=',
    validation: [],
    hideInForm: false,
    hideInSearch: false,
    hideInTable: false,
    enum: '1:one\n2:two\n3:three',
    defaultValue: '1',
    isKey: false,
    null: false,
    sqlType: 'varchar',
    sqlLength: 50,
  },
  {
    valueType: 'money',
    title: '金额输入框',
    dataIndex: 'money',
    select: '=',
    validation: [],
    hideInForm: false,
    hideInSearch: false,
    hideInTable: false,
    enum: '',
    defaultValue: '1',
    isKey: false,
    null: false,
    sqlType: 'decimal',
    sqlLength: 10,
  },
  {
    valueType: 'select',
    title: '下拉框',
    dataIndex: 'select',
    select: '=',
    validation: [],
    hideInForm: false,
    hideInSearch: false,
    hideInTable: false,
    enum: '1:one\n2:two\n3:three',
    defaultValue: '1',
    isKey: false,
    null: false,
    autoIncrement: false,
    sqlLength: 50,
  },
  {
    valueType: 'date',
    title: '日期',
    dataIndex: 'date',
    select: '=',
    validation: [],
    hideInForm: false,
    hideInSearch: false,
    hideInTable: false,
    isKey: false,
    null: false,
    sqlType: 'date',
  },
  {
    valueType: 'dateTime',
    title: '日期时间',
    dataIndex: 'dateTime',
    select: '=',
    validation: [],
    hideInForm: false,
    hideInSearch: false,
    hideInTable: false,
    isKey: false,
    null: false,
    sqlType: 'datetime',
  },
]

/**
 * 默认表格配置
 */
export const defaultTableSetting: OnlineType.TableConfig = {
  bordered: false,
  size: 'middle',
  showHeader: false,
  rowSelectionShow: false,
  addShow: false,
  deleteShow: false,
  editShow: false,
  optionsShow: true,
  options: {
    density: true,
    search: false,
    fullScreen: false,
    setting: true,
    reload: true
  },
  headerTitle: '表格标题',
  tooltip: '表格 tooltip',
  searchShow: true,
  search: {
    searchText: '查询',
    resetText: '重置',
    span: 6,
    layout: 'vertical',
    filterType: 'query'
  },
  paginationShow: true,
  pagination: {
    size: 'default',
  }
}

/**
 * 默认CRUD 配置
 */
export const defaultCRUDConfig: OnlineType.CrudConfig = {
  name: 'TableName',
  controllerPath: '',
  modelPath: '',
  validatePath: '',
  pagePath: '',
  autoDeletetime: false
}

/**
 * 默认配置
 */
export const defaultTableConfig: OnlineType.OnlineTableType = {
  tableSetting: defaultTableSetting,
  crudConfig: defaultCRUDConfig,
  columns: [],
  id: '',
}
